RW Client - Modify KTOR to Add Credentials for Web Api cookie use case
BuddyTV/ktor pull request #4
Opened 2022-02-21 14:22 UTC by davidfgc

Why
---

- This is required for the cookies to work

How
---

- Adding it in the HttpRequestData.toRaw extension method

Side effects
---

- Unknown

**Subsystem**
Client/Server, related modules

**Motivation**
Describe what problem this PR solves and why it is important. Refer to a bug/ticket #.

**Solution**
Describe your solution.

2022-02-24 01:23 UTC, ravihp approved these changes

2022-02-24 01:24 UTC, ravihp requested changes
oops. approved by mistake. This needs latest ktor main branch with coroutines for IDE issue fixes.

2022-03-02 18:05 UTC, davidfgc commented
> oops. approved by mistake. This needs latest ktor main branch with coroutines for IDE issue fixes.

@ravihp isn't part of another issue? this is only the credentials stuff, isn't it?

2022-05-19 17:53 UTC, ravihp commented
already in vizio-2.0.1

2022-05-19 17:53 UTC, closed without merging